package LP_DEFAULT

import com.thirdpillar.foundation.model.*;
import com.thirdpillar.codify.loanpath.model.*;
import com.thirdpillar.foundation.service.LookupService;
import com.thirdpillar.codify.loanpath.model.WorkflowStatus;
import org.apache.commons.lang.RandomStringUtils;
import org.apache.commons.lang.StringUtils;

import function com.thirdpillar.foundation.rules.RuleFunctions.logDebug;
import java.util.ArrayList;
import java.util.List;
import java.util.Calendar;


rule "Default User profile"
    agenda-group "NEW"
      when
        #condition
        user:User() 
      then
      
      	#Status
      	WorkflowStatus status = (WorkflowStatus) LookupService.getResult("WorkflowStatus.byStatusKey", "statusKey", "USER_STATUS_INACTIVE");
        user.setWfStatus(status);

      	#User Type
        AttributeChoice userType = (AttributeChoice)LookupService.getResult("AttributeChoice.byKey", "key","USER_TYPE_INTERNAL");
        user.setUserType(userType);
      	
        #User Source 
        AttributeChoice userSource = (AttributeChoice)LookupService.getResult("AttributeChoice.byKey", "key","USER_SOURCE_INTERNAL");
        user.setUserSource(userSource);
        
        #Temporary password
        if(StringUtils.isEmpty(user.getPassword())) {
          user.setPassword(RandomStringUtils.randomAlphanumeric(12));

          // When lastPasswordResetDate=null, forces password change on first login. 
          user.setLastPasswordResetDate(null);
        }

        #System user
        user.setSystemUser(false);
		
        #Profile
        TimeZone tz = (TimeZone)LookupService.getResult("TimeZone.byIsoCode", "isoCode","America/Los_Angeles");
        user.setTimeZone(tz);
        
        Language l = (Language)LookupService.getResult("Language.byIsoCode", "isoCode","EN");
        user.setLanguage(l);

        Currency c = (Currency)LookupService.getResult("Currency.byIsoCode", "isoCode","USD");
        user.setCurrency(c);

        user.setEmailEnabled(true);
		

end
